spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/webshop
    username: root
    password: root
  thymeleaf:
    cache: false
  resources:
    add-mappings: true
  application:
    name: webshop


